name: Deploy with PowerShell

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, staging, prod)"
        required: true
        default: "dev"
      version:
        description: "App version to deploy"
        required: false

jobs:
  export:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PowerShell to export CSV
        shell: pwsh
        run: |
          $data = @(
              [PSCustomObject]@{ Id = 1; Name = "Alice"; Phone = "555-111" }
              [PSCustomObject]@{ Id = 2; Name = "Bob"; Phone = "555-222" }
          )
          $data | Export-Csv -Path "output.csv" -NoTypeInformation
