name: Get Job Documents Queue

on:
  workflow_dispatch:
    inputs:
        job-id:
            description: Job ID to filter by Documents.
            required: true
            type: string
            default: "99d90c89-3ab0-46c1-9404-afa65084b0f2"
        cid:
            description: Authentication.
            required: true
            type: string
            default: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjMwQUE4NUQxREQwMDk3Qjg0Q0E0REE4M0NENDc4RDkxQzVEM0VERjgiLCJ4NXQiOiJNS3FGMGQwQWw3aE1wTnFEelVlTmtjWFQ3ZmciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJSZWxhdGl2aXR5IiwibmJmIjoxNzU5NDk1MzU3LCJpYXQiOjE3NTk0OTUzNTcsImV4cCI6MTc1OTQ5NTY1NywiYXVkIjoiYmQxMGE2MGQtYjhlYy00OTI4LTg0ZWUtNmZjNGYzMGQ5NjEyIiwiYW1yIjpbInB3ZCJdLCJub25jZSI6IjYzODk1MDkyMTQyNjU4OTI0Ny5ZV1U1TkRRMU9XRXRZak14TnkwMFpXSTFMVGc1T0dZdE5qQXpaRFk0WlRJME5qVmtabUprTURnM01qTXRZV000TWkwMFltTmlMVGs0T1RVdE9EVmlaRGMzTnpJME5UaG0iLCJhdF9oYXNoIjoib21EVmo0WUZ3Zl9KQ1NXZDJrWGxLZyIsInNpZCI6IkEwQzE3NEI4OTkzOTQyN0E1NzU1MTU3ODc0MjZFMzhGIiwic3ViIjoiYW5naXJhcy5rcmlzaGFuYW5AcmVsYXRpdml0eS5jb20iLCJhdXRoX3RpbWUiOjE3NTk0OTUzNTYsImlkcCI6ImxvY2FsIiwicmVsX3VhaSI6IjEwNTQwNTQiLCJyZWxfdW4iOiJhbmdpcmFzLmtyaXNoYW5hbkByZWxhdGl2aXR5LmNvbSIsInJlbF91Zm4iOiJBbmdpcmFzIiwicmVsX3VsbiI6IktyaXNoYW5hbiIsInJlbF9hY2Nlc3MiOiJHcmFudEFjY2VzcyIsInJlbF9haWQiOiJkMjY0MGRiMi02ZTdmLTQ1MWYtODMxOC02YmVhNDM2MGU5MTYiLCJyZWxfaW5zIjoiYjUyZDdlZGItMGEyNi00ODY3LTk2YTUtNTYwMzE3YmM5ZjIxIiwicmVsX29yaWdpbiI6IjE2Ny4xMDMuNTQuMTE5In0.2sCxuZqmOqKnB6z87gocw1B5oJ-uEx3dwyQjQwbxwmQrJsPu7K9ZUxsgC-RRrxAzbgvfzbiwcM7eHBQTMIamElAeBUeOzAF13mLU2H0PKGa_6jIzFfz-QvYzPa4yg_LAZyfriM7Sd4WsQZl8rt_-bzHQuBlQKC7JtTyer3VvJbqn-vZVaXP0AGjwOY4O59TVcpbeKcpjO3Wx_bfHalAr-3JRvK2h0564Km3bn65nZVBI-gKc6iXH7fsrh-IpU0wMBep-S2TzW1ahwJHeU6-7W5XpOU29EnmYVoYWq4KFMlPsYTLzixplYVzSEnMeFAA6HT-s7sxEFqxNTJo9wSfe9g"

jobs:
  run-script:
    name: Get PDF Job Documents Queue in Tenant's environment
    runs-on: windows-latest
    steps:
      - name: Checkout Only Scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/
      - name: Print Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Job ID: ${{ inputs['job-id'] }}"
      - name: Get PDF Job Document Queue
        shell: pwsh
        run: |
          .\scripts\GetJobDocumentsQueue.ps1 `
            -RmsArrayJson '[ "https", "esus019064-t042.r1.kcura.com" ]' `
            -CidToken '${{ inputs['cid'] }}' `
            -JobId '${{ inputs['job-id'] }}' `
            -OutputPath 'jobdocumentqueue_output.txt'

      - name: Upload Job Documents Queue Output
        uses: actions/upload-artifact@v4
        with:
          name: jobdocumentqueue_output
          path: jobdocumentqueue_output.txt
