name: Get Job Documents Queue

on:
  workflow_dispatch:
    inputs:
        job-id:
            description: Job ID to filter by Documents.
            required: true
            type: string
            default: ""

jobs:
  run-script:
    name: Get PDF Job Documents Queue in Tenant's environment
    steps:
      - name: Get PDF Job Document Queue
        shell: pwsh
        run: |
          .\scripts\GetJobDocumentsQueue.ps1 `
            -RmsArrayJson '${{ steps.get_tenant_instance_id.outputs.results }}' `
            -CidToken '${{ steps.get_token.outputs.token }}' `
            -$JobId '${{ inputs['job-id'] }}' `
            -OutputPath 'jobdocumentqueue_output.csv'

      - name: Upload Job Documents Queue Output
        uses: actions/upload-artifact@v4
        with:
          name: jobdocumentqueue_output
          path: jobdocumentqueue_output.csv
