name: Get Job Documents Queue

on:
  workflow_dispatch:
    inputs:
        job-id:
            description: Job ID to filter by Documents.
            required: true
            type: string
            default: "99d90c89-3ab0-46c1-9404-afa65084b0f2"
        cid:
            description: Authentication.
            required: true
            type: string
            default: ""

jobs:
  run-script:
    name: Get PDF Job Documents Queue in Tenant's environment
    runs-on: ubuntu-latest
    steps:
      - name: Get PDF Job Document Queue
        shell: pwsh
        run: |
          .\GetJobDocuments.ps1 `
            -RmsArrayJson '[ "https", "esus019064-t042.r1.kcura.com" ]' `
            -CidToken '${{ inputs['cid'] }}' `
            -$JobId '${{ inputs['job-id'] }}' `
            -OutputPath 'jobdocumentqueue_output.txt'

      - name: Upload Job Documents Queue Output
        uses: actions/upload-artifact@v4
        with:
          name: jobdocumentqueue_output
          path: jobdocumentqueue_output.txt
