name: Get Job Documents Queue

on:
  workflow_dispatch:
    inputs:
        job-id:
            description: Job ID to filter by Documents.
            required: true
            type: string
            default: "99d90c89-3ab0-46c1-9404-afa65084b0f2"
        cid:
            description: Authentication.
            required: true
            type: string
            default: ""

jobs:
  run-script:
    name: Get PDF Job Documents Queue in Tenant's environment
    runs-on: windows-latest
    steps:
      - name: Checkout Only Scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/
      - name: Print Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Job ID: ${{ inputs['job-id'] }}"
      - name: Get PDF Job Document Queue
        shell: pwsh
        run: |
          .\scripts\GetJobDocumentsQueue.ps1 `
            -RmsArrayJson '[ "https", "esus019064-t042.r1.kcura.com" ]' `
            -CidToken '${{ inputs['cid'] }}' `
            -JobId '${{ inputs['job-id'] }}' `
            -OutputPath 'jobdocumentqueue_output.csv'

      - name: Upload Job Documents Queue Output
        uses: actions/upload-artifact@v4
        with:
          name: jobdocumentqueue_output
          path: jobdocumentqueue_output.csv
